# Generated by Django 2.2 on 2021-11-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employeeId', models.CharField(max_length=10, unique=True)),
                ('grade', models.IntegerField()),
                ('date', models.DateField()),
                ('doj', models.DateField()),
                ('dor', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.PositiveIntegerField(default=30)),
                ('basic_salary', models.PositiveIntegerField()),
                ('HRA', models.PositiveIntegerField()),
                ('allowance', models.PositiveIntegerField()),
                ('Incentives', models.PositiveIntegerField()),
                ('gift_voucher', models.PositiveIntegerField(blank=True, null=True)),
                ('medical', models.PositiveIntegerField()),
                ('internet', models.PositiveIntegerField(default=1000)),
                ('professional_tax', models.PositiveIntegerField()),
                ('TDS', models.PositiveIntegerField()),
                ('PF', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=15)),
                ('total_earnings', models.PositiveIntegerField()),
                ('total_deduction', models.PositiveIntegerField()),
                ('net_salary', models.PositiveIntegerField()),
                ('created_at', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payslip.Employee')),
            ],
        ),
    ]
