# Generated by Django 2.2 on 2021-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
